<? $AUTH=true;
	require_once 'app/init.php';
	require_once 'app/data.php';
	require_once 'lib/maketable/maketable.php';

	include 'app/begin.php';
	maketable(array(
		'self'=>$URL.'/foods-table',
		'key'=>'id',
		'join'=>array(
			'product'=>array(),
			array('person',array('id'=>'product.maker'),'left'),
		),
		'where'=>array(
			'product.type=1',
			#'product.parent IS NULL',
		),
		'columns'=>array(
			'product.barcode'=>array('Barcode',
				'search'=>'left',
				'edit'=>'none',
				'width'=>'85px',
			),

			#'person.name'=>array('Producer',
			#	'person_name_html',
			#	'search'=>'mid',
			#),

			'product.name'=>array('Name', 'product_name_html',
				'search'=>'mid',
				'width'=>'280px',
			),

			'product.energy*100/product.sample_weight'=>array('Energy',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'kcal',
				'width'=>'60px',
			),
			#'product.water*100/product.sample_weight'=>array('H₂O',
			#	'f'=>'quantity_html',
			#	'class'=>'number',
			#	'tip'=>'Νερό',
			#	'postfix'=>'g',
			#	'width'=>'35px',
			#),
			'product.proteins*100/product.sample_weight'=>array('Prot.',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'g',
				'width'=>'35px',
			),
			'product.carbohydrates*100/product.sample_weight'=>array('Carb.',
				'tip'=>'Carbohydrates',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'g',
				'width'=>'35px',
			),
			'product.sugars*100/product.sample_weight'=>array('Sug.',
				'tip'=>'Sugars',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'g',
				'width'=>'35px',
			),
			'product.fats*100/product.sample_weight'=>array('Fat',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'g',
				'width'=>'35px',
			),
			'product.fats_saturated*100/product.sample_weight'=>array('S.Fat.',
				'tip'=>'Saturated fatty acids',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'g',
				'width'=>'35px',
			),
			'product.total_fiber*100/product.sample_weight'=>array('Fiber',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'g',
				'width'=>'35px',
			),
			'product.sodium*100/product.sample_weight'=>array('Na',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>'mg',
				'width'=>'35px',
			),
			'product.calcium*100/product.sample_weight'=>array('Ca',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>'mg',
				'width'=>'35px',
			),
			'product.phosphorus*100/product.sample_weight'=>array('P',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>'mg',
				'width'=>'35px',
			),
			#'product.magnesium*100/product.sample_weight'=>array('Mg',
			#	'f'=>'quantity_html',
			#	'class'=>'number',
			#	#'postfix'=>'mg',
			#	'width'=>'35px',
			#),
			'product.iron*100/product.sample_weight'=>array('Fe',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>'mg',
				'width'=>'35px',
			),
			'product.a*100/product.sample_weight'=>array('A',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>' mg',
				'width'=>'35px',
			),
			'product.b1*100/product.sample_weight'=>array('B₁',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>' mg',
				'width'=>'35px',
			),
			'product.b2*100/product.sample_weight'=>array('B₂',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>' mg',
				'width'=>'35px',
			),
			#'product.b3*100/product.sample_weight'=>array('B₃',
			#	'f'=>'quantity_html',
			#	'class'=>'number',
			#	#'postfix'=>' mg',
			#	'width'=>'35px',
			#),
			#'product.b5*100/product.sample_weight'=>array('B₅',
			#	'f'=>'quantity_html',
			#	'class'=>'number',
			#	#'postfix'=>' mg',
			#	'width'=>'35px',
			#),
			'product.b6*100/product.sample_weight'=>array('B₆',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>' mg',
				'width'=>'35px',
			),
			#'product.b7*100/product.sample_weight'=>array('B₇',
			#	'f'=>'quantity_html',
			#	'class'=>'number',
			#	#'postfix'=>' mg',
			#	'width'=>'35px',
			#),
			'product.b9*100/product.sample_weight'=>array('B₉',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'μ',
				'width'=>'35px',
			),
			'product.b12*100/product.sample_weight'=>array('B₁₂',
				'f'=>'quantity_html',
				'class'=>'number',
				'postfix'=>'μ',
				'width'=>'35px',
			),
			'product.c*100/product.sample_weight'=>array('C',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>' mg',
				'width'=>'35px',
			),
			#'product.d*100/product.sample_weight'=>array('D',
			#	'f'=>'quantity_html',
			#	'class'=>'number',
			#	'postfix'=>'μ',
			#	'width'=>'35px',
			#),
			'product.e*100/product.sample_weight'=>array('E',
				'f'=>'quantity_html',
				'class'=>'number',
				#'postfix'=>' mg',
				'width'=>'35px',
			),
		),
		'userorder'=>true,
		'orderby'=>'product.name',
		'userorder'=>true,
	));
	return include 'app/end.php';
?>
