#!/usr/bin/python
#
# * reads schema.txt as standard input and UPPERCASE.txt files in working directory
# * produces SQL statements for importing database into MySQL or PostgreSQL
#
# with one argument it outputs only CREATE TABLE statements
#
# with two arguments it outputs ALTER TABLE statements for modifying the first
# schema to match the second
#
# TODO secondary keys and database indices
#
# XXX assumes empty fields in nullable foreign key VARCHAR columns are null and
# not empty
#
# XXX any table reference cycles might not be handled properly
#
# XXX cannot drop foreign keys
#
# XXX renaming a column will cause it to be dropped; KEEP NAMES UNCHANGED
#
# XXX changing primary keys is not implemented
#
import sys
import re

tableprefix = ''  # prefix will be added to table names and foreign key table names (i.e. imported tables can only have foreign keys among themselves)

droptables = 1  # DROP the tables that appear in the old schema but not in the new
dropbeforecreate = 0  # output "DROP TABLE IF EXISTS" statements before any "CREATE TABLE"s
writeschema = 1  # output "CREATE TABLE" and "ALTER TABLE" statements
writeforeignkeys = 1  # add "FOREIGN KEY"s when new schema has them but old doesn't. TRICK: to delay adding indices until after data has been imported, set this to 0 and then to 1

writedata = 1  # simple "INSERT" statements for data
varchar_foreign_nulls = 1  # empty values for *foreign key* nullable VARCHAR fields will be turned into NULL, to avoid violating foreign key constraints
varchar_normal_nulls = 0  # empty values for *all other* nullable VARCHAR fields will be turned into NULL

#
# for MySQL
#
fieldquote = '`'
commentsyntax = 0
recordgroup = 32  # to avoid MySQL "packet too large" errors
mysql = 1
typemap = {
	'A':'VARCHAR',
	'VARCHAR':'VARCHAR',
	'TEXT':'TEXT',

	'BOOL':'TINYINT',
	'BOOLEAN':'TINYINT',
	'INT':'INT',
	'N':'DECIMAL',

	'FLOAT':'FLOAT',
	'FLOAT8':'DOUBLE',
	'DOUBLE':'DOUBLE',

	'DATE':'DATE',
	'TIME':'TIME',
	'TIMESTAMP':'TIMESTAMP',
}

#
# for PostreSQL (NOT TESTED)
#
#fieldquote = '"'
#commentsyntax = 1
#recordgroup = 32
#typemap = {
#	'A':'VARCHAR',
#	'VARCHAR':'VARCHAR',
#	'TEXT':'TEXT',
#
#	'BOOL:'BOOLEAN',
#	'BOOLEAN':'BOOLEAN',
#	'INT':'INT',
#	'N':'DECIMAL',
#
#	'FLOAT':'FLOAT',
#	'FLOAT8':'FLOAT8',
#	'DOUBLE':'FLOAT8',
#
#	'DATE':'DATE',
#	'TIME':'TIME',
#	'TIMESTAMP':'TIMESTAMP WITH TIME ZONE',
#}

def readschema(f,fn):
	lineno = 0
	tables = {}
	curtable = None

	try:
		while True:
			line = f.readline()
			if not line: break
			lineno=lineno+1

			line = line.strip('\r\n')
			if not line: continue

			i = line.find('--')
			if i<>-1:
				line,comment = line[:i],line[i+2:]
			else:
				comment = None

			line = line.strip()
			if not line: continue

			words = line.split()

			if len(words)==1:
				tablename = words[0]
				if not re.match('[A-Za-z_][A-Za-z0-9_]*$', tablename):
					raise Exception('can only handle alphanumeric characters and underscores in table names: %s'%line)

				curtable = tables[tablename] = []
			else:
				if len(words)<2 or len(words)>5:
					raise Exception('expected: sqlfield {N|A|TYPE} [{len|digits.digits} [{Y|N} [reftable.refkey]]]')

				if len(words[1])==2 and words[1][-1:]=='*':
					keyfield = True
					words[1] = words[1][:-1]
				elif len(words)>=3 and len(words[2])>=2 and words[2][-1:]=='*':
					keyfield = True
					words[2] = words[2][:-1]
				else:
					keyfield = False

				#
				# [0] field name
				#
				fname = words[0].split('.')
				if len(fname)>2 or not fname[0] or not fname[-1]:
					raise Exception('expected [TABLE.]FIELD as first word')

				field = [fname[-1]]

				#
				# [1] type
				#
				if typemap.get(words[1])==None:
					raise Exception("unrecognized type (second word): %s"%line)

				field.append(typemap[words[1]])

				#
				# [2] length or digits.decimals
				#
				if len(words)>=3:
					if words[2] == '-':
						field.append(None)
					else:
						field.append(tuple(map(int,words[2].split('.'))))
						while len(field[2]) and field[2][-1]==0:
							field[2] = field[2][:-1]
						if len(field[2])==1:
							field[2] = field[2][0]
				elif field[1]=='DECIMAL' or field[1]=='VARCHAR':
					raise Exception('need field length for DECIMAL and VARCHAR fields as third word')

				#
				# [3] nullable
				#
				if len(words)>=4:
					if words[3]=='Y':
						field.append(True)
					elif words[3]=='N':
						field.append(False)
					else:
						raise Exception("expected nullable flag ('Y' or 'N') as fourth word (defaults to 'N' if missing)")
				else:
					field.append(False)

				#
				# [4] reftable.refkey
				#
				if len(words)>=5:
					field.append(words[4].split('.'))
					if len(field[4])<>2:
						raise Exception("expected REFTABLE.REFKEY as fifth word")
				else:
					field.append(None)

				#
				# [5] keyfield?
				#
				field.append(keyfield)

				#
				# [6] comment
				#
				field.append(comment)

				if len(fname)==2:
					tables[fname[0]].append(field)
				else:
					curtable.append(field)
	except Exception, x:
		sys.stderr.write('%s:%d: %s\n\n'%(fn,lineno,'; '.join(map(str,x.args))))
		raise

	return tables

def sqlfield(name):
	return fieldquote+name.replace(fieldquote,fieldquote+fieldquote)+fieldquote

def sqlstring(s):
	return "'"+s.replace("'","''").replace('\\','\\\\')+"'"

def iskey(words):
	return words[5]

def field_def(words,singlekeyfield=0):
	t = [sqlfield(words[0])]

	if words[1]=='VARCHAR':
		t.append('VARCHAR(%d)'%words[2])
	else:
		if type(words[2])==tuple:
			s = ','.join(map(str,words[2]))
		elif words[2]<>None:
			s = str(words[2])
		else:
			s = None

		if s<>None:
			t.append('%s(%s)'%(words[1],s))
		else:
			t.append(words[1])

	if words[3]:
		t.append('NULL')
	else:
		t.append('NOT NULL')

	if singlekeyfield and words[5]:
		t.append('PRIMARY KEY')

	if commentsyntax==0 and words[6]<>None:
		t.append('COMMENT '+sqlstring(words[6]))

	return ' '.join(t)

def field_def_pkey(s):
	return field_def(s,1)

def typed_value(value,field):
	if field[3] and value=='':
		if field[1]=='DECIMAL':
			return 'NULL'
		elif field[1]=='VARCHAR':
			if field[4]<>None:
				if varchar_foreign_nulls:
					return 'NULL'
			else:
				if varchar_normal_nulls:
					return 'NULL'

	return sqlstring(value)

def print_table(tablename,fields):
	filename = tablename.upper()+'.txt'
	try:
		f = open(filename,'r')
	except IOError, x:
		return

	lineno = 0
	outlineno = 0
	while True:
		lineno = lineno+1
		line = f.readline()
		if not line: break
		line = line.rstrip('\r\n')

		state = 0
		value = []
		values = []
		for i in range(len(line)):
			c = line[i]
			if state==0:
				if c=='^':
					values.append(''.join(value))
					value = []
				elif c=='~':
					state = 1
				else:
					value.append(c)
			elif state==1:
				if c=='~':
					state = 0
				else:
					value.append(c)

		if state==0:
			values.append(''.join(value))
			value = []
		elif state==1:
			sys.stderr.write('%s:%d: end of line after single ~ quote (assuming end of line closes quote): %s\n'%(filename,lineno, repr(line)))
			values.append(''.join(value))
			value = []

		if len(fields)<>len(values):
			sys.stderr.write('%s:%d: incorrect number of data values (expected %d, got %d; ignoring line): %s\n'%(filename,lineno, len(fields), len(values), repr(line)))
			continue

		if outlineno==0 or (recordgroup>0 and (outlineno%recordgroup)==0):
			if outlineno>0:
				sys.stdout.write(';\n')
			sys.stdout.write('INSERT INTO %s (%s) VALUES\n'%(sqlfield(tableprefix+tablename), ','.join(map(lambda a: sqlfield(a[0]),fields))))
		else:
			sys.stdout.write(',\n')

		sys.stdout.write('\t(%s)'%','.join(map(lambda i: typed_value(values[i],fields[i]), range(len(fields)))))

		outlineno = outlineno + 1

	if outlineno>0:
		sys.stdout.write(';\n')

	f.close()
	sys.stdout.write('\n');

def print_drops(tablename,prevtables,tables,dropped):
	if dropped.get(tablename):
		return
	dropped[tablename] = 1

	hasref = False
	for tablename2,fields2 in tables.items():
		for f2 in fields2:
			if f2[4] and f2[4][0]==tablename:
				print_drops(tablename2,prevtables,tables,dropped)

	if (dropbeforecreate and (prevtables==None or prevtables.get(tablename)==None) and tables.get(tablename)<>None):
		sys.stdout.write('DROP TABLE IF EXISTS %s;\n'%sqlfield(tableprefix+tablename))
		sys.stdout.write('\n')

	elif ((prevtables<>None and prevtables.get(tablename)<>None) and tables.get(tablename)==None):
		sys.stdout.write('DROP TABLE %s;\n'%sqlfield(tableprefix+tablename))
		sys.stdout.write('\n')

def print_schema(tablename,prevtables,tables,written):
	if written.get(tablename)==1: return
	written[tablename] = 1
	fields = tables[tablename]
	for f in fields:
		if f[4]:
			print_schema(f[4][0],prevtables,tables,written)

	#
	# dump table
	#
	keyfields = filter(iskey,fields)

	if prevtables==None or prevtables.get(tablename)==None:
		if len(keyfields)>1:
			commalist = map(field_def,fields)
			commalist.append('PRIMARY KEY (%s)'%','.join(map(lambda a:sqlfield(a[0]),keyfields)))
		else:
			commalist = map(field_def_pkey,fields)

		if writeforeignkeys:
			for f in fields:
				if f[4]:
					commalist.append('FOREIGN KEY (%s) REFERENCES %s(%s)'%(sqlfield(f[0]),sqlfield(tableprefix+f[4][0]),sqlfield(f[4][1])))

		if mysql:
			extra = ' ENGINE = InnoDB';

		if commalist:
			sys.stdout.write('CREATE TABLE %s (\n\t%s\n)%s;\n'%(sqlfield(tableprefix+tablename),',\n\t'.join(commalist),extra))
			if commentsyntax==1:
				for field in fields:
					if field[5]<>None:
						sys.stdout.write('COMMENT ON %s.%s IS %s;\n'%(sqlfield(tablename),sqlfield(field[1]),sqlstring(field[5])));
			sys.stdout.write('\n');
	else:
		prevfields = prevtables[tablename]
		extra = None
		commalist = []
		fa = None
		for f in fields:
			f2 = f[:4]+[None]+f[5:]
			x = zip(prevfields,range(len(prevfields)))
			pfs = filter(lambda pf: pf[0][0]==f[0], x)
			if pfs:
				if pfs[0][1]:
					pfa = prevfields[pfs[0][1]-1][0]
				else:
					pfa = None
				pf = pfs[0][0]
				pf2 = pf[:4]+[None]+pf[5:]

				if (f2,fa)<>(pf2,pfa):
					s = 'MODIFY COLUMN '+field_def(f)
					if fa==None:
						s = s + ' FIRST'
					else:
						s = s + ' AFTER ' + sqlfield(fa)
					commalist.append(s)

				if writeforeignkeys and pf[4]==None and f[4]<>None:
					commalist.append('ADD FOREIGN KEY (%s) REFERENCES %s(%s)'%(sqlfield(f[0]),sqlfield(tableprefix+f[4][0]),sqlfield(f[4][1])))
					if mysql:
						extra = 'ENGINE = InnoDB'
			else:
				s = 'ADD COLUMN '+field_def(f)
				if fa==None:
					s = s + ' FIRST'
				else:
					s = s + ' AFTER ' + sqlfield(fa)
				commalist.append(s)
			fa = f[0]
		for pf in prevfields:
			fs = filter(lambda f: pf[0]==f[0], fields)
			if not fs:
				commalist.append('DROP COLUMN '+sqlfield(pf[0]))

		if extra<>None:
			commalist.append(extra)

		if commalist:
			sys.stdout.write('ALTER TABLE %s \n\t%s\n;\n'%(sqlfield(tableprefix+tablename),',\n\t'.join(commalist)))
			sys.stdout.write('\n');

def print_data(tablename,tables,written):
	if written.get(tablename)==1: return
	written[tablename] = 1
	for f in tables[tablename]:
		if f[4]:
			print_data(f[4][0],tables,written)

	#
	# dump table
	#
	print_table(tablename,tables[tablename])

if __name__ == '__main__':
	if len(sys.argv)<2:
		prevtables = None
		tables = readschema(sys.stdin,'<stdin>')

	elif len(sys.argv)==2:
		prevtables = None
		f = open(sys.argv[1],'r')
		tables = readschema(f,sys.argv[1])
		f.close()

	elif len(sys.argv)==3:
		if sys.argv[1]=='-':
			prevtables = readschema(sys.stdin,'<stdin>')
		else:
			f = open(sys.argv[1],'r')
			prevtables = readschema(f,sys.argv[1])
			f.close()
		f = open(sys.argv[2],'r')
		tables = readschema(f,sys.argv[2])
		f.close()

	elif len(sys.argv)==4:
		tableprefix = sys.argv[1]

		if sys.argv[2]=='-':
			prevtables = readschema(sys.stdin,sys.argv[1])
		else:
			f = open(sys.argv[2],'r')
			prevtables = readschema(f,sys.argv[2])
			f.close()

		f = open(sys.argv[3],'r')
		tables = readschema(f,sys.argv[3])
		f.close()

	else:
		sys.stderr.write('syntax: %s [[[PREFIX] {PREVSCHEMA|-}] SCHEMA]\n'%sys.argv[0])
		sys.exit(1)

	if mysql:
		sys.stdout.write('SET NAMES utf8;\n\n');

	if droptables:
		dropped={}
		for tablename in tables:
			print_drops(tablename,prevtables,tables,dropped)
		if prevtables<>None:
			for tablename in prevtables:
				print_drops(tablename,prevtables,tables,dropped)

	if writeschema:
		written = {}
		for tablename,fields in tables.items():
			print_schema(tablename,prevtables,tables,written)

	if writedata:
		written = {}
		for tablename,fields in tables.items():
			print_data(tablename,tables,written)
